### PR TITLE
- Added streaming progress Fixes #27

### LINKED ISSUE #27: Add support for AVPlayer progressive streaming
It would be nice if video player shows the progress of streaming videos.

### PR DESCRIPTION
**Pull request by mzeeshanid**
- Fixed few warning
- Added TYMProgressBarView for streaming progress and playing progress

### CODE REVIEW

**Comment by 0x0c** [comment]
@mzeeshanid Thank you for your pull request.
It's very nice but I need you to fix small bug that when a video is not loaded, a slider position is not good.
I want that the slider position when a video is not loaded, is set at 0.0.
See this screen shot, then please fix this issue;)

screen shot 2015-12-03 at 3 31 43 pm

**Comment by mzeeshanid** [comment]
I added the following things:
* Error delegates (in case if player was failed to load the video).
* Loading indicator and loading state is added for player.
* Fixed the slider position problem.
* Fixed the error where all the information about the track immediately not available. [More info](http://stackoverflow.com/questions/20581567/avplayer-and-avfoundationerrordomain-code-11819)

**Comment by 0x0c** [comment]
Thanks for your PR.
I want to change minimum track tint color.
Can you do this?

**Comment by mzeeshanid** [comment]
Yes I can...

**Comment by 0x0c** [comment]
Please implement this feature.
This is my final request ;)

**Comment by mzeeshanid** [comment]
Example for customising the progress bar:
```objective-c
[[LMMediaPlayerView sharedPlayerView] setProgressBarBorderColor:[UIColor orangeColor]
                                                   innerBorderColor:[UIColor lightGrayColor]
                                                    backgroundColor:[UIColor redColor]
                                                          fillColor:[UIColor magentaColor]
                                                     thumbTintColor:[UIColor greenColor]];
```
Example for customising the progress bar thumb:
```objective-c
[[LMMediaPlayerView sharedPlayerView] setProgressBarThumbImage:[UIImage imageNamed:@"thumb"]];
```

**Comment by 0x0c** [comment]
How to change the color of here?
screen_shot_2015-12-08_at_2_30_38_pm

**Comment by mzeeshanid** [comment]
Set the inner border color and bar fill color:
simulator screen shot 08-dec-2015 10 36 16 am

**Comment by 0x0c** [comment]
I want to change the color like this.
16f2ccda-9d98-11e5-969b-1c9e4def85ce
68747470733a2f2f7261772e6769746875622e636f6d2f307830632f4c4d4d65646961506c617965722f6d61737465722f696d616765732f312e706e67

**Comment by mzeeshanid** [comment]
Ok I got it :)

**Comment by mzeeshanid** [comment]
Updated...

**Comment by 0x0c** [comment]
Perfect!
Thanks a lot.
I will merge this.

**Pull request merged**
